
name: Deploy Lambda
on:
  push:
    branches: [ feature/aws-lambda ]
jobs:
  deploy-lambda:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - run: cp src/sendtweet.py package/sendtweet.py
      - run: cd package/ && zip -r ../package.zip **
      - uses: yvesgurcan/deploy-lambda-function@v0.0.5
        with:
          package: package.zip
          function-name: bezos-net-worth
          AWS_REGION: ${{ secrets.AWS_REGION }}
          AWS_SECRET_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}